# Add a file of this format in your texture packs zip as
# /config/forestry/colour.properties to configure font colours.
# A file at that location inside the zip of the active texture pack
# will take precedence over the default.
#
# Hex format without leading 0x

gui.title=BFBFBF
#gui.screen=001DFF
#gui.table.header=001DFF
#gui.table.row=001DFF
#gui.book=001DFF
gui.worktable.missing=B13E53
#
#gui.beealyzer.binomial=14d50b
#gui.beealyzer.recessive=3687ec
#gui.beealyzer.dominant=ec3661
#
#gui.mail.lettertext=cfa738
#gui.mail.text=6689dc
#
#ledger.error.background=ff3535
#ledger.error.header=e1c92f
ledger.error.text=999999
#
#ledger.hint.background=ea38ff
#ledger.hint.header=e1c92f
ledger.hint.text=999999
#
#ledger.owner.background=ffffff
#ledger.owner.header=e1c92f
#ledger.owner.subheader=aaafb8
ledger.owner.text=999999
#
#ledger.climate.background=35a4ff
#ledger.climate.header=e1c92f
#ledger.climate.subheader=aaafb8
ledger.climate.text=999999
#
#ledger.power.background=d46c1f
#ledger.power.header=e1c92f
#ledger.power.subheader=aaafb8
ledger.power.text=999999
#
#ledger.farm.background=2ca22c
#ledger.farm.header=e1c92f
#ledger.farm.subheader=aaafb8
ledger.farm.text=999999
#
#ledger.search_ingredients.background=ffffff
#ledger.search_ingredients.header=587b96
ledger.search_ingredients.text=999999